#!/usr/bin/env perl
use warnings;
use strict;
use FindBin;
use File::Spec;
# add current directory on the fly
use lib File::Spec->catfile($FindBin::Bin);
# import all
use branchLib;
use controller;
use pathLib;
use commitTreeLib;
use fileLib;

use textLib;
use typeLib;
# this script for testing

if (is_ancestor_of_some_branch("branch1")){
  dd_err("true");
}
else {
  dd_err("false");
}
