#!/usr/bin/env perl
use warnings;
use strict;
use FindBin;
use File::Spec;
# add current directory on the fly
use lib File::Spec->catfile($FindBin::Bin);
# import all
use branchLib;
use controller;
use pathLib;
use commitTreeLib;
use fileLib;
use helperLib;
use textLib;
use typeLib;
# this script for testing
my @src = ("b", "d","f");
my @dest = ("a","b","c", "d");


my %diff = diff(@src,@dest);

my @result =  patch(@src,%diff);

dd_arr("Result",@result);
# dd_hash("diff", %diff);
# foreach (keys %hash) {
#   print "$_ :",$src[$_ - 1], "\n";
# }
