#!/usr/bin/env perl
use warnings;
use strict;
use FindBin;
use File::Spec;
# add current directory on the fly
use lib File::Spec->catfile($FindBin::Bin);
# import all
use branchLib;
use controller;
use pathLib;
use commitTreeLib;
use fileLib;
use helperLib;
use textLib;
use typeLib;
# this script for testing
my @src = ("a","b","c", "d");
my @dest = ("b", "d");


my %hash = diff(@src,@dest);

dd_hash("diff", %hash);
# foreach (keys %hash) {
#   print "$_ :",$src[$_ - 1], "\n";
# }
